feed-the-people/Front-End

src/mockData.js

-Need mock data to build more dynamic components.
- creates files for #16, #11, and #10

Create basic data we should expect from the API.

---

src/components/RecipeCard/RecipeCard.css
src/components/RecipeCard/RecipeCard.js
src/components/RecipeCard/RecipeCard.test.js

Setting up the `RecipeCard` component!
I have built out and base styled the `RecipeCard` component.

Recipe Card Base

---

src/components/CallToAction/CallToAction.css
src/components/CallToAction/CallToAction.js
src/components/MainPage/MainPage.js
src/components/ProfilePage/ProfilePage.css
src/components/ProfilePage/ProfilePage.js
src/components/RecipeBook/RecipeBook.css
src/components/RecipeBook/RecipeBook.js
src/components/RecipeCard/RecipeCard.css
src/components/RecipeCard/RecipeCard.js

- We weren't ready to connect our API for global recipes.
-Making sure signing in "did something" for user experince
-Refactoring recipe cards to be prop bases
-Refactoring the recipebook to only show up for a signed in and displaying their data.\
- Maked sure there is user sign in conditionals for some of what is accessible
- Maked recipe cards dynamic and flexible 
- Has loading messages for async fetch resolving
-broke the call to action into it's own recyclable component from profilepage

Formatting

---

src/APICalls.js
src/components/App/App.js
src/components/MainPage/MainPage.js

-Displaying the global store of recipes on the main page.
-Connected the API call to the actual render of the components.
-closes #29

Connect global recipes

---

src/APICalls.js
src/components/App/App.js
src/components/ProfilePage/ProfilePage.js
src/components/SignIn/SignInPage.js

- We need to allow a user to sign in and store that user some way between page navigations
-implimenting local storage to store the user token and the user information.
-closes #30 
-closes #20

User login

---

src/APICalls.js
src/components/App/App.js
src/components/Profile/Profile.css
src/components/Profile/Profile.js
src/components/ProfilePage/ProfilePage.js
src/components/SignIn/SignInPage.js

-The user needs to be able to see their own profile information, and before they are able to edit them down the road.
-closes #62

Profile render

---

src/components/CallToAction/CallToAction.js
src/components/MainPage/MainPage.js
src/components/MainPage/MainPage.test.js

Testing for `MainPage` component is completed! 
Unit and integration tests are needed
Unit and integration tests have been written.
Revolves #65 
Revoles #64 
Fixed a type in `CallToAction.js` on line 8.

Unit & Integration Testing ; MainPage

---

src/APICalls.js
src/components/App/App.js

getUserWithRecipes should return a user's bought recipes
Changed the BE to include a user's bought recipes on getUser
updated getUserWithRecipes on FE to reflect the BE change

Add a users bought recipes to getUserWithRecipes

---

src/APICalls.js
src/components/App/App.js

A user should be able to update a recipe
Added updateRecipe to APICalls.js
verified that it works from the update_recipe_branch on BE (this branch has been merged and should be up on heroku soon)

Add updateRecipe to APICalls

---

src/components/SignUp/SignUpPage.js

Disable the Sign Me Up! button on the user sign up page until all input fields are filled. 
closes #82 
Created a new function that checks for state of all fields .

Disable Sign Up Button

---

src/components/SignIn/SignInPage.js

User should not be able to submit Sign In until all fields filled.
- Use disableForm function 
- Add boolean value to submit button
closes #81

Disable submit button until all fields filled

---

src/APICalls.js
src/components/App/App.js
src/components/MainPage/MainPage.js
src/components/RecipeBook/RecipeBook.js
src/components/RecipeCard/RecipeCard.js
src/components/RecipePage/RecipePage.js
src/components/RecipePage/RecipePage.test.js

- need to connect recipe pages to their recipe card button
- and needed dynamic rendering of specific recipes
- used match.params from the url to pass in a prop of recipe id
- rendered recipe cards with id
- connected the BE to fetch a specific recipe for the page

Dynamic recipe page

---

src/APICalls.js
src/components/PurchaseModal/PurchaseModal.css
src/components/PurchaseModal/PurchaseModal.js
src/components/RecipePage/RecipePage.js
src/index.css

- the user needs to indicate they donated for a recipe
- the main recipe page should display if/when a user has purched a recipe
- built in the api call to "purchase" a recipe
- build in functionality to chenc if the current recipe is in the user's purchased recipe array

Payment prompt

---

src/components/RecipeBook/RecipeBook.js

-bought recipes weren't displaying for a user's recipe book
-added a conditional on how to map over data based on the kind being accessed

Add conditional for data being returned on API.

---

src/APICalls.js
src/components/MainPage/MainPage.js
src/components/RecipeCard/RecipeCard.js

Rating of recipe was hardcoded. 
Rating will now display its' rating or display "Not yet rated" if value is null.

Display Recipe Rating

---

src/components/RecipePage/RecipePage.css
src/components/RecipePage/RecipePage.js

Styling on the Recipe Show Page

Style recipe show

---

src/components/RecipeForm/RecipeForm.css
src/components/RecipeForm/RecipeForm.js

Styling on Recipe Update page.

Recipe update styling

---

src/APICalls.js
src/components/MainPage/MainPage.js
src/components/MainPage/MainPage.test.js
src/components/Profile/Profile.js
src/components/RecipeBook/RecipeBook.css
src/components/RecipeBook/RecipeBook.js
src/components/RecipeBook/RecipeBook.test.js
src/components/RecipeCard/RecipeCard.js
src/components/RecipeCard/RecipeCard.test.js
src/components/RecipeForm/RecipeForm.js
src/components/RecipePage/RecipePage.js

Attempted to remove Give N Get Recipe button if recipe is owned or created by current user. Works only after the state of localStoage user is update which I couldnt get to update properly. It will only update after the second purchase and so on of a recipe.
Commented out test code and performed manual testing in some cases. Also deleted many console.logs in code. Lastly, changed the footer routes to maintain same order for consistency

Display buttons

---

src/components/Profile/Profile.css
src/components/Profile/Profile.js
src/components/RecipeForm/RecipeForm.js

Profile restyle

---

src/components/RecipeForm/RecipeForm.css

footer was running over
removed padding.

remove padding from footer

---

src/components/Footer/Footer.css
src/components/RecipeForm/RecipeForm.css
src/components/RecipeForm/RecipeForm.js
src/components/SignIn/SignInPage.js
src/components/SignUp/SignUpPage.js

Put forms in tables. Note forms still not working this is just for styling.

Form Clean Up

---

src/components/App/App.js
src/components/App/App.test.js
src/components/CallToAction/CallToAction.js
src/components/CallToAction/CallToAction.test.js
src/components/Footer/Footer.js
src/components/Footer/Footer.test.js
src/components/MainPage/MainPage.js
src/components/MainPage/MainPage.test.js
src/components/Profile/Profile.test.js
src/components/PurchaseModal/PurchaseModal.test.js
src/components/RecipeBook/RecipeBook.js
src/components/RecipeBook/RecipeBook.test.js
src/components/RecipeCard/RecipeCard.js
src/components/RecipeCard/RecipeCard.test.js
src/components/RecipeForm/RecipeForm.js
src/components/RecipeForm/RecipeForm.test.js
src/components/RecipePage/RecipePage.js
src/components/RecipePage/RecipePage.test.js
src/components/SignIn/SignInPage.js
src/components/SignIn/SignInPage.test.js
src/components/SignUp/SignUpPage.js
src/components/SignUp/SignUpPage.test.js

-better orient what to work on between now and emo comp
-start adding basic code annotations

Annotations

---

src/APICalls.js
src/components/RecipeCard/RecipeCard.js
src/components/RecipeForm/RecipeForm.js
src/components/SignUp/SignUpPage.js

- #104 
- #103 
- closes #103 
- closes #104 
By refactoring to have an {error:} returned on errors, ther is better sad path handling.
There was also a typo where the await was removed on one form.

Form fixes

---

src/APICalls.js
src/components/MainPage/MainPage.js
src/components/RecipeBook/RecipeBook.js
src/components/RecipeCard/RecipeCard.js
src/components/RecipeForm/RecipeForm.js
src/components/SignUp/SignUpPage.js

- #101 
- closes #101 but allow for dynamic rendering of what is in the button box but not the functionality
- added in updates of the user in local storage on page loads for recipe book and main page

Recipe button fix
